# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Firebase Publish React
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        # Firebase token for CI
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
        # If true, then action will use its own firebase. If fase, reuse firebase from previous steps
        install-firebase: false
        # If true, build application before deploying. If false, use the build directory from previous steps
        build-application: ./build
